"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys

sys.setrecursionlimit(2000)
print(sys.getrecursionlimit())

APP = ['main.py']
DATA_FILES = ["Settings.json"]
OPTIONS = {
    'argv_emulation': True
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
