# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 841)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QFrame(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(609, 9, 391, 381))
        self.image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image.setObjectName("image")
        self.preview3d = QtWidgets.QFrame(self.centralwidget)
        self.preview3d.setGeometry(QtCore.QRect(30, 390, 571, 381))
        self.preview3d.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.preview3d.setFrameShadow(QtWidgets.QFrame.Raised)
        self.preview3d.setObjectName("preview3d")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(760, 680, 161, 71))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 581, 121))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.browseFiles = QtWidgets.QPushButton(self.widget)
        self.browseFiles.setObjectName("browseFiles")
        self.gridLayout_2.addWidget(self.browseFiles, 1, 0, 1, 1)
        self.getData = QtWidgets.QPushButton(self.widget)
        self.getData.setObjectName("getData")
        self.gridLayout_2.addWidget(self.getData, 0, 2, 1, 1)
        self.fileName = QtWidgets.QTextBrowser(self.widget)
        self.fileName.setObjectName("fileName")
        self.gridLayout_2.addWidget(self.fileName, 1, 1, 1, 2)
        self.dataInput = QtWidgets.QTextEdit(self.widget)
        self.dataInput.setObjectName("dataInput")
        self.gridLayout_2.addWidget(self.dataInput, 0, 0, 1, 2)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(320, 150, 281, 41))
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.exportPath_2 = QtWidgets.QTextBrowser(self.widget1)
        self.exportPath_2.setObjectName("exportPath_2")
        self.gridLayout_3.addWidget(self.exportPath_2, 0, 1, 1, 1)
        self.selectExportPath = QtWidgets.QPushButton(self.widget1)
        self.selectExportPath.setObjectName("selectExportPath")
        self.gridLayout_3.addWidget(self.selectExportPath, 0, 0, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(20, 200, 581, 171))
        self.widget2.setObjectName("widget2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.description = QtWidgets.QTextBrowser(self.widget2)
        self.description.setObjectName("description")
        self.gridLayout.addWidget(self.description, 1, 1, 1, 2)
        self.DescriptionShow = QtWidgets.QTextBrowser(self.widget2)
        self.DescriptionShow.setObjectName("DescriptionShow")
        self.gridLayout.addWidget(self.DescriptionShow, 1, 0, 1, 1)
        self.NameShow = QtWidgets.QTextBrowser(self.widget2)
        self.NameShow.setObjectName("NameShow")
        self.gridLayout.addWidget(self.NameShow, 0, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget2)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout.addWidget(self.textBrowser_2, 2, 0, 1, 1)
        self.IDnumber = QtWidgets.QTextBrowser(self.widget2)
        self.IDnumber.setObjectName("IDnumber")
        self.gridLayout.addWidget(self.IDnumber, 2, 1, 1, 2)
        self.Name = QtWidgets.QTextBrowser(self.widget2)
        self.Name.setObjectName("Name")
        self.gridLayout.addWidget(self.Name, 0, 1, 1, 2)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(20, 150, 291, 41))
        self.widget3.setObjectName("widget3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.quality = QtWidgets.QTextBrowser(self.widget3)
        self.quality.setObjectName("quality")
        self.gridLayout_4.addWidget(self.quality, 0, 0, 1, 1)
        self.qualitySlider = QtWidgets.QSlider(self.widget3)
        self.qualitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.qualitySlider.setObjectName("qualitySlider")
        self.gridLayout_4.addWidget(self.qualitySlider, 0, 1, 1, 1)
        self.widget4 = QtWidgets.QWidget(self.centralwidget)
        self.widget4.setGeometry(QtCore.QRect(740, 420, 211, 81))
        self.widget4.setObjectName("widget4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.vanderwaals = QtWidgets.QRadioButton(self.widget4)
        self.vanderwaals.setObjectName("vanderwaals")
        self.gridLayout_5.addWidget(self.vanderwaals, 0, 0, 1, 1)
        self.vanderwaals_2 = QtWidgets.QRadioButton(self.widget4)
        self.vanderwaals_2.setObjectName("vanderwaals_2")
        self.gridLayout_5.addWidget(self.vanderwaals_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.getData.clicked.connect(self.dataInput.copy) # type: ignore
        self.browseFiles.clicked.connect(self.fileName.reload) # type: ignore
        self.qualitySlider.valueChanged['int'].connect(self.quality.reload) # type: ignore
        self.selectExportPath.clicked.connect(self.exportPath_2.reload) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Generuj Model"))
        self.browseFiles.setText(_translate("MainWindow", "Procházet soubory"))
        self.getData.setText(_translate("MainWindow", "Získat data"))
        self.exportPath_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/...</p></body></html>"))
        self.selectExportPath.setText(_translate("MainWindow", "Složka pro export"))
        self.quality.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Kvalita:</p></body></html>"))
        self.vanderwaals.setText(_translate("MainWindow", "Van der Waalsův model"))
        self.vanderwaals_2.setText(_translate("MainWindow", "Ball stick model"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
